import type { Point } from './types';
import { MAX_FRAME_DT } from './constants';
export const getScaledFrameDt = (realFrameDt: number, timeScale: number, maxFrameDt = MAX_FRAME_DT) => Math.min(maxFrameDt, Math.max(0, realFrameDt)) * timeScale;
export const integrateVelocity = (velocity: Point, acceleration: Point, friction: number, dt: number): Point => { const f = Math.pow(friction, dt * 60); return { x: velocity.x * f + acceleration.x * dt, y: velocity.y * f + acceleration.y * dt }; };
export const integratePosition = (position: Point, velocity: Point, dt: number): Point => ({ x: position.x + velocity.x * dt, y: position.y + velocity.y * dt });
export const simulateLinearDisplacement = (velocity: Point, realElapsedSeconds: number, timeScale: number): Point => ({ x: velocity.x * realElapsedSeconds * timeScale, y: velocity.y * realElapsedSeconds * timeScale });
export type DragState = { id: string | null; type: 'ball' | 'portal' | 'handle' | null };
type Body = { x: number; y: number; oldX: number; oldY: number; vx?: number; vy?: number };
export const getPinnedBallIndex = (dragState: DragState): number => { if (dragState.type !== 'ball' || dragState.id === null) return -1; const n = Number(dragState.id); return Number.isInteger(n) && n >= 0 ? n : -1; };
export const syncPinnedBallToPointer = <T extends Body>(bodies: T[], dragState: DragState, pointer: Point, frameDt?: number): number => { const i = getPinnedBallIndex(dragState); const b = bodies[i]; if (!b) return -1; const px = b.x; const py = b.y; b.oldX = px; b.oldY = py; b.x = pointer.x; b.y = pointer.y; if (frameDt && frameDt > 0 && b.vx !== undefined && b.vy !== undefined) { b.vx = (b.x - px) / frameDt; b.vy = (b.y - py) / frameDt; } return i; };
